# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Olsthoorn
email: rolsthoorn12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robert Olsthoorn | Developer, Traveler, Learner, Family Man
baseurl: ""
url: "http://robertolsthoorn.com"
github_username:  rolstenhouse
linkedin_username: rolstenhouse

self_description:
  Learner, Hacker, Traveler

# Build settings
markdown: kramdown

# include: ['_projects']

exclude: [node_modules]

collections:
  projects:
    output: true
    permalink: /projects/:path/
  work:
    output: true
    permalink: /work/:path/
  education:
    output: true
    permalink: /education/:path/
  extracurricular:
    output: true
    permalink: /extracurricular/:path/


comfortableLanguages: ['C++', 'Java', 'C#', 'Javascript']
